### ISSUE TITLE
Any support for Visual Studio Code?

### ISSUE THREAD

**Issue by RexHell** [domchen/typescript-plus#9]
I tried typescript-plus with reorderFiles on my project.
It works well on compiling.
But the intellisense in Visual Studio Code remains the original behavior, that I have to add /// <reference path="xxxxx.ts" /> to make the editor correctly load type definitions.
I suspect tsserver is used for parsing, so I replace C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript with typescript-plus but it still remains the original behavior.
Is the tsserver also need to be modified or is my configuration not correct?

**Comment by domchen** [comment]
@RexHell Hmmm... I didn't modify anything of tsserver, so it will not reorder any files automatically by default. But I haven't had any problem like you described. I think the intelli-sense in Visual Studio Code should work fine even without the reordering feature since it works perfectly this way in Webstorm. Actually, I am not familiar with VS Code, maybe you can send me a simple example project, I will have a look at it and try to find what's the problem inside. My email is: dom@idom.me

**Comment by RexHell** [comment]
I think I found the problem in my configuration. The tsconfig.json is not put in the folder that is opened by Visual Studio Code. After I move it to the right place, it all works like a charm. Except there is a problem saying "error TS5023: Unknown compiler option 'reorderFiles'", but it can be easily handled by replacing C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript with typescript-plus.
Thank you very much.

**Comment by domchen** [comment]
You are welcome. I am glad that you found the problem :)
